update doc for release 0.6.0
openelb/website pull request #100
Opened 2024-05-29 09:59 UTC by renyunkang

2024-05-31 02:20 UTC, chaunceyjiang commented on content/en/docs/getting-started/configuration/configure-openelb-for-multi-router-clusters.md
> +2. Run the following command to edit the openelb-speaker Daemonset:
```suggestion
2. Run the following command to edit the openelb-speaker DaemonSet:
```

2024-05-31 02:20 UTC, chaunceyjiang commented on content/en/docs/getting-started/configuration/configure-openelb-for-multi-router-clusters.md
> +3. In the openelb-speaker Daemonset YAML configuration, add the following fields under `spec:template:spec`:
```suggestion
3. In the openelb-speaker DaemonSet YAML configuration, add the following fields under `spec:template:spec`:
```

2024-05-31 09:41 UTC, zhuxiujuan28 requested changes

2024-05-31 09:41 UTC, zhuxiujuan28 commented on content/en/docs/getting-started/usage/openelb-ip-address-assignment.md
> +  When the number of available EIPs is greater than 1, there will be some priority selection to choose the final EIP to use.
```suggestion
  When the number of available EIPs is greater than 1, the final EIP will be chosen according to the priorities. 
```

2024-05-31 09:41 UTC, zhuxiujuan28 commented on content/en/docs/getting-started/usage/use-openelb-in-layer-2-mode.md
> +## Step 1: Make sure layer2 mode is enabled
```suggestion
## Step 1: Make Sure Layer2 Mode is Enabled
```

2024-05-31 09:41 UTC, zhuxiujuan28 commented on content/en/docs/getting-started/usage/use-openelb-in-vip-mode.md
> +## Step 1: Make sure vip mode is enabled
```suggestion
## Step 1: Make Sure Vip Mode is Enabled
```

2024-05-31 09:44 UTC, zhuxiujuan28 requested changes

2024-05-31 09:44 UTC, zhuxiujuan28 commented on content/en/docs/getting-started/configuration/configure-multiple-openelb-replicas.md
> +In layer2 or vip modes, if you want only certain nodes to handle traffic, you can also use `nodeSelector`, `Node Affinity`, or `Taints and Tolerations` to schedule `openelb-speaker` on specific nodes
```suggestion
In Layer 2 or VIP mode, if you want only certain nodes to handle traffic, you can also use `nodeSelector`, `Node Affinity`, or `Taints and Tolerations` to schedule `openelb-speaker` on specific nodes. 
```

2024-06-03 07:05 UTC, zhuxiujuan28 commented
/lgtm

2024-06-14 08:46 UTC, merged